# Deep Learning: Convolutional Neural Networks

**Duration:** 5 min

This module delves into Convolutional Neural Networks (CNNs), a class of deep neural networks most commonly applied to analyzing visual imagery. Understanding CNNs is crucial for tasks like image recognition, object detection, and even natural language processing. This module will cover the fundamental concepts, architectures, and practical implementations of CNNs using Python.

## Understanding Convolutional Layers

Convolutional layers are the core building blocks of CNNs. These layers apply a convolution operation to the input, passing the result to the next layer. The convolution operation involves a filter (or kernel) that slides over the input, performing element-wise multiplication and summing the results. This process helps in extracting features like edges, textures, and shapes from the input data.

In [ ]:
import numpy as np

# Define a simple 3x3 filter
filter = np.array([[1, 0, -1], [1, 0, -1], [1, 0, -1]])

# Define a 5x5 input matrix
input_matrix = np.array([[0, 1, 2, 3, 4],
                         [5, 6, 7, 8, 9],
                         [10, 11, 12, 13, 14],
                         [15, 16, 17, 18, 19],
                         [20, 21, 22, 23, 24]])

# Perform convolution
output = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        output[i, j] = np.sum(filter * input_matrix[i:i+3, j:j+3])

print(output)

> **Try it in Google Colab:** [![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/shastrula/ailearningclub-courses/blob/main/ai-fundamentals/mod-10.ipynb)

```
[[ 30.  42.  36.]
 [ 84. 126. 108.]
 [138. 198. 180.]]
```

## Pooling Layers

Pooling layers are used to reduce the spatial dimensions (width and height) of the input volume for the subsequent convolutional layers. This helps in reducing the number of parameters and computations in the network, thereby controlling overfitting. The most common form of pooling is max pooling, where the maximum value from the region covered by the filter is taken.

In [ ]:
import numpy as np

# Define a 4x4 input matrix
input_matrix = np.array([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]])

# Perform max pooling with a 2x2 filter and stride of 2
output = np.zeros((2, 2))
for i in range(0, 4, 2):
    for j in range(0, 4, 2):
        output[i//2, j//2] = np.max(input_matrix[i:i+2, j:j+2])

print(output)

> **💡 Tip:** When designing CNNs, it's important to balance the depth of the network with the complexity of the task. Too shallow networks may underfit, while too deep networks may overfit and become computationally expensive.

<div class="quiz" data-correct="1">
  <p class="font-semibold mb-3">❓ What is the primary purpose of convolutional layers in a CNN?</p>
  <div class="space-y-2">
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386962496" value="0">
      <span>To increase the dimensionality of the input</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386962496" value="1">
      <span>To extract features from the input</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386962496" value="2">
      <span>To fully connect all neurons in the network</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386962496" value="3">
      <span>To perform non-linear transformations</span>
    </label>
  </div>
  <button class="quiz-btn mt-3 px-4 py-2 bg-blue-600 text-white rounded text-sm font-medium hover:bg-blue-700">Check Answer</button>
  <p class="quiz-result text-sm mt-2 hidden"></p>
</div>

<div class="quiz" data-correct="2">
  <p class="font-semibold mb-3">❓ What is the main function of pooling layers in a CNN?</p>
  <div class="space-y-2">
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386963008" value="0">
      <span>To increase the number of parameters</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386963008" value="1">
      <span>To extract features from the input</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386963008" value="2">
      <span>To reduce the spatial dimensions of the input</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386963008" value="3">
      <span>To perform non-linear transformations</span>
    </label>
  </div>
  <button class="quiz-btn mt-3 px-4 py-2 bg-blue-600 text-white rounded text-sm font-medium hover:bg-blue-700">Check Answer</button>
  <p class="quiz-result text-sm mt-2 hidden"></p>
</div>